---
# Mac Mini Setup Playbook
# Automated setup for macOS development environment

- name: Configure Mac Mini
  hosts: localhost
  connection: local
  become: false

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Ensure Homebrew is installed
      ansible.builtin.stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Install Homebrew if not present
      ansible.builtin.shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not homebrew_check.stat.exists
      changed_when: true

  roles:
    - role: homebrew
      tags: ['homebrew', 'packages']
    - role: apps
      tags: ['apps', 'casks']
    - role: development
      tags: ['development', 'dev']
    - role: dotfiles
      tags: ['dotfiles', 'config']
    - role: macos-defaults
      tags: ['macos', 'defaults', 'preferences']

  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          Mac Mini setup complete!
          You may need to restart your terminal or log out/in for some changes to take effect.
